export default {
    one: [
        // { message: {}, flag: true, name: 'A030.6下壳体涂胶及拧紧', left: '40', top: '19' },
        // { message: {}, flag: true, name: 'A030.5下壳体涂胶及拧紧', left: '38', top: '24' },
        // { message: {}, flag: true, name: 'A030.4下壳体涂胶及拧紧', left: '36', top: '29' },
        // { message: {}, flag: true, name: 'A030.3下壳体涂胶及拧紧', left: '34', top: '35' },
        { message: {}, flag: true, name: '下壳体涂胶及拧紧', left: '32', top: '40' },
        // { message: {}, flag: true, name: 'A030.1下壳体涂胶及拧紧', left: '30', top: '46' },
        // { message: {}, flag: true, name: 'A510.1EOL测试', left: '48', top: '30' },
        // { message: {}, flag: true, name: 'A510.2EOL测试', left: '47', top: '32' },
        // { message: {}, flag: true, name: 'A510.3EOL测试', left: '46', top: '34' },
        { message: {}, flag: true, name: 'EOL测试', left: '46', top: '37' },
        // { message: {}, flag: true, name: 'A510.5EOL测试', left: '45', top: '39' },
        // { message: {}, flag: true, name: 'A510.12EOL测试', left: '53', top: '31' },
        // { message: {}, flag: true, name: 'A510.11EOL测试', left: '53', top: '34' },
        // { message: {}, flag: true, name: 'A510.10EOL测试', left: '52', top: '36' },
        // { message: {}, flag: true, name: 'A510.9EOL测试', left: '51', top: '38' },
        // { message: {}, flag: true, name: 'A510.8EOL测试', left: '51', top: '40' },
        // { message: {}, flag: true, name: 'A510.7EOL测试', left: '50', top: '43' },
        // { message: {}, flag: true, name: 'A500.1密封测试', left: '56', top: '24' },
        // { message: {}, flag: true, name: 'A500.2密封测试', left: '57', top: '24' },
        // { message: {}, flag: true, name: 'A500.3密封测试', left: '59', top: '25' },
        // { message: {}, flag: true, name: 'A500.4密封测试', left: '59.5', top: '25' },
        { message: {}, flag: true, name: '密封测试', left: '62.5', top: '26' },
        // { message: {}, flag: true, name: 'A500.6密封测试', left: '64', top: '26' },
        { message: {}, flag: true, name: '自动选择', left: '59', top: '31' },
        { message: {}, flag: true, name: '底板FDS', left: '57', top: '45' },
        // { message: {}, flag: true, name: 'A430底板FDS', left: '56', top: '49' },
        { message: {}, flag: true, name: '拧紧上盖普通螺栓', left: '65', top: '55' },
        // { message: {}, flag: true, name: 'A350拧紧上盖FDS螺栓', left: '69', top: '26' },
        { message: {}, flag: true, name: '拧紧上盖普通螺栓', left: '68', top: '29' },
        // { message: {}, flag: true, name: 'A350拧紧上盖FDS螺栓', left: '68', top: '33' },
        // { message: {}, flag: true, name: 'A350拧紧上盖FDS螺栓', left: '67', top: '37' },
        // { message: {}, flag: true, name: 'A290.10.IL测试', left: '76', top: '27' },
        // { message: {}, flag: true, name: 'A290.8.IL测试', left: '76', top: '29' },
        // { message: {}, flag: true, name: 'A290.7.IL测试', left: '75', top: '31' },
        // { message: {}, flag: true, name: 'A290.6.IL测试', left: '75', top: '33' },
        { message: {}, flag: true, name: 'IL测试', left: '75', top: '35' },
        // { message: {}, flag: true, name: 'A290.4.IL测试', left: '74', top: '37' },
        // { message: {}, flag: true, name: 'A290.3.IL测试', left: '74', top: '39' },
        // { message: {}, flag: true, name: 'A290.2.IL测试', left: '74', top: '41' },
        // { message: {}, flag: true, name: 'A290.1.IL测试', left: '73', top: '44' },
    ],
    two: [
        { message: {}, flag: false, name: 'KCBWA11', left: '41', top: '17' },
        { message: {}, flag: false, name: 'KCBWA12', left: '49', top: '20' },
        { message: {}, flag: false, name: 'KCBWA13', left: '55', top: '16' },
        { message: {}, flag: false, name: 'KCBWA14', left: '68', top: '22' },
        { message: {}, flag: false, name: 'KCBWA15', left: '69', top: '19' },
        { message: {}, flag: false, name: 'KCBWA23', left: '43', top: '28' },
        { message: {}, flag: false, name: 'KCBWA22', left: '56', top: '31' },
        { message: {}, flag: false, name: 'KCBWA21', left: '70', top: '35' },
    ]
}
