export default {
    one: [
        { message: {}, flag: true, name: '粗细密封1', left: '39', top: '14' },
        { message: {}, flag: true, name: '粗细密封2', left: '39', top: '17' },
        { message: {}, flag: true, name: '粗细密封3', left: '36', top: '18' },
        { message: {}, flag: true, name: '大返修1', left: '49', top: '30' },
        { message: {}, flag: true, name: '面漆准备1', left: '45', top: '30' },
        { message: {}, flag: true, name: '面漆准备2', left: '48', top: '34' },
        { message: {}, flag: true, name: '大返修2', left: '44', top: '34' },
        { message: {}, flag: true, name: '面漆准备3', left: '45', top: '36' },
        { message: {}, flag: true, name: '大返修3', left: '44', top: '37' },
        { message: {}, flag: true, name: '电池控制1', left: '80', top: '27' },
        { message: {}, flag: true, name: '电池控制2', left: '79', top: '29' },
        { message: {}, flag: true, name: '电池控制3', left: '78', top: '32' },
        { message: {}, flag: true, name: '报交1.1', left: '76', top: '39' },
        { message: {}, flag: true, name: '报交1.2', left: '75', top: '41' },
        { message: {}, flag: true, name: '报交2.1', left: '73', top: '44' },
        { message: {}, flag: true, name: '报交2.2', left: '72', top: '45' },
        { message: {}, flag: true, name: '报交3.1', left: '69', top: '47' },
        { message: {}, flag: true, name: '报交3.2', left: '69', top: '49' },
    ],
    two: [
        { message: {}, flag: false, name: '面漆1', left: '35', top: '21' },
        { message: {}, flag: false, name: '面漆2', left: '32', top: '25' },
        { message: {}, flag: false, name: '面漆3', left: '27', top: '31' },
        { message: {}, flag: false, name: 'PVC烘房1', left: '40', top: '17' },
        { message: {}, flag: false, name: 'PVC烘房2', left: '41', top: '19' },
        { message: {}, flag: false, name: '电池1', left: '41', top: '19' },
        { message: {}, flag: false, name: '电池2', left: '47', top: '13' },
        { message: {}, flag: false, name: '电泳烘房1', left: '58', top: '17' },
        { message: {}, flag: false, name: '电泳烘房2', left: '57', top: '18' },
        { message: {}, flag: false, name: '电泳烘房3', left: '55', top: '19' },
        { message: {}, flag: false, name: '电泳烘房4', left: '54', top: '20' },
        { message: {}, flag: false, name: '面漆烘房1', left: '64', top: '31' },
        { message: {}, flag: false, name: '面漆烘房2', left: '61', top: '35' },
        { message: {}, flag: false, name: '面漆烘房3', left: '61', top: '44' },


    ]
}
